services:
  pipeline:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: savencia-pipeline  
    env_file:
      - .env
    volumes:
      - ./gcp_sa_savencia.json:/app/gcp_sa_savencia.json:ro
    networks:
      - portefolio-network
    restart: "no"

networks:
  portefolio-network:
    external: true